### ISSUE TITLE
The Evaluation Results in CAMPUS GARDEN2 Dataset

### ISSUE THREAD

**Issue by sontaptrung** [chengche6230/ReST#17]
Hello @chengche6230,

I trust this message reaches you in good spirits. To start, I'd like to convey my gratitude for your outstanding contributions. Your dedication is truly appreciated.

**I have conducted an evaluation on the CAMPUS - GARDEN2 dataset on [Website](https://bitbucket.org/merayxu/multiview-object-tracking-dataset/src/master/) and rename file in dataset followed format:**
> **view-HC1.txt -> view-HC0.txt**
> **view-HC2.txt -> view-HC1.txt**
> **view-HC3.txt -> view-HC2.txt**
> **view-HC4.txt -> view-HC3.txt**

**with the following configuration:**

```
MODEL:
  DEVICE: "cuda"
  DEVICE_ID: ('0')
  MODE: 'test'
  DETECTION: 'gt' # {'gt'}
  RESUME: false
  LAST_CKPT_FILE: './'

DATASET:
  DIR: './datasets/'
  NAME: 'CAMPUS'
  SEQUENCE: ['Garden2'] # {'Garden1' | 'Garden2' | 'Parkinglot'}
  CAMS: 4
  TOTAL_FRAMES: 6000 # 'Garden1':2849, 'Garden2': 6000, 'Parkinglot': 6475

FE: # Feature Extractor
  CHOICE: 'CNN'
  INPUT_SIZE: (256, 128)

SOLVER:
  TYPE: 'SG' # {'SG': Spatial Graph, 'TG': Temporal Graph}
  EPOCHS: 100
  EVAL_EPOCH: 2
  BATCH_SIZE: 100
  LR: 0.01 # Learning Rate
  MAX_PASSING_STEPS: 4
  W: 3 # Temporal Window Size
  W_TEST: 5
  FOCAL_ALPHA: 0.98
  FOCAL_GAMMA: 5

OUTPUT:
  VISUALIZE: False
  LOG: True
  CKPT_DIR: './logs/ckpts'
  INFERENCE_DIR: './logs/inference'

TEST:
  CKPT_FILE_SG: '/content/drive/MyDrive/MTMOT/ReST/weights/CAMPUS_Garden2_SG_epoch12_train80.pth'
  CKPT_FILE_TG: '/content/drive/MyDrive/MTMOT/ReST/weights/CAMPUS_Garden2_TG_epoch6_train80.pth'
  FRAME_START: 4800 # 'Garden1': 2280; 'Garden2': 4800; 'Parkinglot': 5828
  EDGE_THRESH: 0.9
```
**I obtained the following results:** ![image](https://github.com/chengche6230/ReST/assets/126637335/4cb98db1-31a3-4f7b-9153-2a0a57ad3315)
**when compared to the results in your paper:**
![image](https://github.com/chengche6230/ReST/assets/126637335/690a91d0-2e6f-46bf-835f-636494cb3a4e)![image](https://github.com/chengche6230/ReST/assets/126637335/8c98d45d-c46d-442c-9417-aae3fffa40e0)\
I notice differences between the obtained metrics. Could I have missed something in the evaluation process?
